import type { SymbolSpec } from "./types";

export const SYMBOLS: SymbolSpec[] = [
  {
    id: "ES",
    label: "ES",
    name: "E-mini S&P 500",
    kind: "futures",
    digits: 2,
    tick: 0.25,
    pointValue: 50,
    typical: 7676,
    barVol: 0.00042,
    gapSigma: 0.0034,
    pTrend: 0.28,
    pBreakout: 0.3,
    pReversal: 0.16,
    yahoo: "ES=F",
    tv: "CME_MINI:ES1!",
  },
  {
    id: "NQ",
    label: "NQ",
    name: "E-mini Nasdaq 100",
    kind: "futures",
    digits: 2,
    tick: 0.25,
    pointValue: 20,
    typical: 29464,
    barVol: 0.00058,
    gapSigma: 0.0048,
    pTrend: 0.26,
    pBreakout: 0.36,
    pReversal: 0.14,
    yahoo: "NQ=F",
    tv: "CME_MINI:NQ1!",
  },
  {
    id: "YM",
    label: "YM",
    name: "E-mini Dow",
    kind: "futures",
    digits: 0,
    tick: 1,
    pointValue: 5,
    typical: 52626,
    barVol: 0.00038,
    gapSigma: 0.003,
    pTrend: 0.3,
    pBreakout: 0.26,
    pReversal: 0.16,
    yahoo: "YM=F",
    tv: "CBOT_MINI:YM1!",
  },
  {
    id: "CL",
    label: "CL",
    name: "Crude Oil",
    kind: "futures",
    digits: 2,
    tick: 0.01,
    pointValue: 1000,
    typical: 99.9,
    barVol: 0.00092,
    gapSigma: 0.007,
    pTrend: 0.22,
    pBreakout: 0.28,
    pReversal: 0.24,
    yahoo: "CL=F",
    tv: "NYMEX:CL1!",
  },
  {
    id: "GC",
    label: "GC",
    name: "Gold",
    kind: "futures",
    digits: 1,
    tick: 0.1,
    pointValue: 100,
    typical: 4410,
    barVol: 0.00048,
    gapSigma: 0.0042,
    pTrend: 0.34,
    pBreakout: 0.24,
    pReversal: 0.12,
    yahoo: "GC=F",
    tv: "COMEX:GC1!",
  },
  {
    id: "AAPL",
    label: "AAPL",
    name: "Apple",
    kind: "stocks",
    digits: 2,
    tick: 0.01,
    pointValue: 1,
    typical: 334.2,
    barVol: 0.00055,
    gapSigma: 0.0065,
    pTrend: 0.24,
    pBreakout: 0.28,
    pReversal: 0.18,
    yahoo: "AAPL",
    tv: "NASDAQ:AAPL",
  },
  {
    id: "NVDA",
    label: "NVDA",
    name: "NVIDIA",
    kind: "stocks",
    digits: 2,
    tick: 0.01,
    pointValue: 1,
    typical: 219.3,
    barVol: 0.00095,
    gapSigma: 0.011,
    pTrend: 0.3,
    pBreakout: 0.34,
    pReversal: 0.14,
    yahoo: "NVDA",
    tv: "NASDAQ:NVDA",
  },
  {
    id: "TSLA",
    label: "TSLA",
    name: "Tesla",
    kind: "stocks",
    digits: 2,
    tick: 0.01,
    pointValue: 1,
    typical: 364.6,
    barVol: 0.00115,
    gapSigma: 0.013,
    pTrend: 0.22,
    pBreakout: 0.32,
    pReversal: 0.22,
    yahoo: "TSLA",
    tv: "NASDAQ:TSLA",
  },
  {
    id: "SPY",
    label: "SPY",
    name: "S&P 500 ETF",
    kind: "stocks",
    digits: 2,
    tick: 0.01,
    pointValue: 1,
    typical: 765.5,
    barVol: 0.00036,
    gapSigma: 0.0032,
    pTrend: 0.28,
    pBreakout: 0.28,
    pReversal: 0.16,
    yahoo: "SPY",
    tv: "AMEX:SPY",
  },
  {
    id: "EURUSD",
    label: "EURUSD",
    name: "Euro / Dollar",
    kind: "forex",
    digits: 5,
    tick: 0.00001,
    pointValue: 100000,
    typical: 1.1609,
    barVol: 0.00022,
    gapSigma: 0.0014,
    pTrend: 0.2,
    pBreakout: 0.22,
    pReversal: 0.2,
    yahoo: "EURUSD=X",
    tv: "FX:EURUSD",
  },
  {
    id: "GBPUSD",
    label: "GBPUSD",
    name: "Cable",
    kind: "forex",
    digits: 5,
    tick: 0.00001,
    pointValue: 100000,
    typical: 1.3524,
    barVol: 0.00028,
    gapSigma: 0.0018,
    pTrend: 0.22,
    pBreakout: 0.24,
    pReversal: 0.2,
    yahoo: "GBPUSD=X",
    tv: "FX:GBPUSD",
  },
  {
    id: "BTCUSD",
    label: "BTCUSD",
    name: "Bitcoin",
    kind: "crypto",
    digits: 1,
    tick: 0.5,
    pointValue: 1,
    typical: 77437,
    barVol: 0.00085,
    gapSigma: 0.0085,
    pTrend: 0.32,
    pBreakout: 0.3,
    pReversal: 0.14,
    yahoo: "BTC-USD",
    tv: "BITSTAMP:BTCUSD",
  },
];

export const SYMBOL_MAP = Object.fromEntries(SYMBOLS.map((s) => [s.id, s])) as Record<
  string,
  SymbolSpec
>;

const ALIASES: Record<string, string> = {
  "NQ=F": "NQ",
  MNQ: "NQ",
  "MNQ=F": "NQ",
  "ES=F": "ES",
  MES: "ES",
  "MES=F": "ES",
  "YM=F": "YM",
  MYM: "YM",
  "MYM=F": "YM",
  "CL=F": "CL",
  "GC=F": "GC",
  BTC: "BTCUSD",
  "BTC-USD": "BTCUSD",
  "EURUSD=X": "EURUSD",
  "GBPUSD=X": "GBPUSD",
};

export function resolveSymbolId(raw: string): string | null {
  const id = raw.trim().toUpperCase();
  if (!id) return null;
  if (SYMBOL_MAP[id]) return id;
  if (ALIASES[id]) return ALIASES[id]!;
  const root = id.replace(/[FGHJKMNQUVXZ]\d{1,2}$/i, "");
  if (root !== id && SYMBOL_MAP[root]) return root;
  return null;
}

export function getSymbol(id: string): SymbolSpec {
  const resolved = resolveSymbolId(id);
  return (resolved ? SYMBOL_MAP[resolved] : null) ?? SYMBOLS[0]!;
}

export const WATCHLIST_DEFAULT = ["ES", "NQ", "CL", "GC", "NVDA", "BTCUSD"];
