/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppChartsRouteImport } from './routes/app/charts'
import { Route as AppJournalRouteImport } from './routes/app/journal'
import { Route as AppMentorRouteImport } from './routes/app/mentor'
import { Route as AppPlaybooksRouteImport } from './routes/app/playbooks'
import { Route as AppPropRouteImport } from './routes/app/prop'
import { Route as AppReplayRouteImport } from './routes/app/replay'
import { Route as AppReportsRouteImport } from './routes/app/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChartsRoute = AppChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMentorRoute = AppMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlaybooksRoute = AppPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPropRoute = AppPropRouteImport.update({
  id: '/prop',
  path: '/prop',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/charts': typeof AppChartsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/prop': typeof AppPropRoute
  '/app/replay': typeof AppReplayRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/charts': typeof AppChartsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/prop': typeof AppPropRoute
  '/app/replay': typeof AppReplayRoute
  '/app/reports': typeof AppReportsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/charts': typeof AppChartsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/prop': typeof AppPropRoute
  '/app/replay': typeof AppReplayRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/charts'
    | '/app/journal'
    | '/app/mentor'
    | '/app/playbooks'
    | '/app/prop'
    | '/app/replay'
    | '/app/reports'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analytics'
    | '/app/charts'
    | '/app/journal'
    | '/app/mentor'
    | '/app/playbooks'
    | '/app/prop'
    | '/app/replay'
    | '/app/reports'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/charts'
    | '/app/journal'
    | '/app/mentor'
    | '/app/playbooks'
    | '/app/prop'
    | '/app/replay'
    | '/app/reports'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/charts': {
      id: '/app/charts'
      path: '/charts'
      fullPath: '/app/charts'
      preLoaderRoute: typeof AppChartsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mentor': {
      id: '/app/mentor'
      path: '/mentor'
      fullPath: '/app/mentor'
      preLoaderRoute: typeof AppMentorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/playbooks': {
      id: '/app/playbooks'
      path: '/playbooks'
      fullPath: '/app/playbooks'
      preLoaderRoute: typeof AppPlaybooksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/prop': {
      id: '/app/prop'
      path: '/prop'
      fullPath: '/app/prop'
      preLoaderRoute: typeof AppPropRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/replay': {
      id: '/app/replay'
      path: '/replay'
      fullPath: '/app/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppChartsRoute: typeof AppChartsRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMentorRoute: typeof AppMentorRoute
  AppPlaybooksRoute: typeof AppPlaybooksRoute
  AppPropRoute: typeof AppPropRoute
  AppReplayRoute: typeof AppReplayRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppChartsRoute: AppChartsRoute,
  AppJournalRoute: AppJournalRoute,
  AppMentorRoute: AppMentorRoute,
  AppPlaybooksRoute: AppPlaybooksRoute,
  AppPropRoute: AppPropRoute,
  AppReplayRoute: AppReplayRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
